---
  - 
    name: Update all packages reference to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - 
    name: Reboot server
    reboot:

  - 
    name: Download CAC installer
    ansible.builtin.get_url:
      url: https://eitcstore01.blob.core.windows.net/installers/{{ cloud_access_installer }}{{ sas_token }}
      dest: /home/{{ username }}

  - 
    name: unarchive tar file
    ansible.builtin.unarchive:
      src: /home/{{ username }}/{{ cloud_access_installer }}
      dest: /home/{{ username }}/
      remote_src: yes

  # Use following task if register to self hosted CAM server
  - 
    name: Execute the command in remote shell; stdout goes to the specified file on the remote 
    shell: /home/{{ username }}/usr/sbin/cloud-access-connector install -t {{ cac_token }} --external-pcoip-ip {{ external_ip }} --cam-url=https://{{ cam_ipaddress }} --cam-insecure --self-signed --accept-policies --reg-code {{ registration_code }} --domain {{ ad_domain }} --sa-user {{ sa_user }} --sa-password {{ sa_password }}
    register: shell_result

  # Use following task if register to Teradici hosted CAM
  # - 
  #   name: Execute the command in remote shell; stdout goes to the specified file on the remote 
  #   shell: /home/{{ username }}/usr/sbin/cloud-access-connector install -t {{ cac_token }} --external-pcoip-ip {{ external_ip }} --self-signed --accept-policies --reg-code {{ registration_code }} --domain {{ ad_domain }} --sa-user {{ sa_user }} --sa-password {{ sa_password }}
  #   register: shell_result

  - 
    name: display stdout of Teradici CAC installation
    ansible.builtin.debug:
        var: shell_result.stdout_lines       
...