---

  - 
    name: "Install required software"
    ansible.builtin.apt:
      name: unzip
      state: present
      update_cache: yes
    register: install_result
    until: install_result is success
    retries: 6
    delay: 10

  - 
    name: "Check if nexis is installed"
    ansible.builtin.stat:
      path: /avid/sbin/nxserver
      get_md5: no
    register: nexis_status

  - 
    name: "Set flag when nexis is already deployed"
    ansible.builtin.set_fact:
      nexis_deployed: true
    when: nexis_status.stat.exists == true 

  - 
    name: "Debug information: Set flag when nexis is already deployed"
    ansible.builtin.debug:
      var: nexis_deployed
      verbosity: 2

...
