---

- 
  name: "Check if Nexis Activation ID is set"
  fail:
    msg: "Nexis Activation ID is not net in < nexis_activation_id >."
  when: (nexis_activation_id is undefined) or nexis_activation_id == ""

- 
  name: "Check if Nexis System ID is set"
  fail:
    msg: "Nexis System ID is not net in < nexis_system_id >."
  when: (nexis_system_id is undefined) or nexis_system_id == ""

...
