---
username: local-admin
ad_domain: poc.internal
sa_user: sa_teradici
sa_password: Password123$
cam_ipaddress: "10.1.3.5"
cac_token: "xxxxxx"
registration_code: "xxxxxx"
external_ip: "xxxxxx"
cloud_access_installer: "cloud-access-connector_85_Linux.tar.gz"
...