---

  - 
    name: "Download Teradici installers"
    win_get_url:
      url: "{{ teradici_installer_url }}"
      dest: "{{ required_software_path }}\\{{ teradici_installer_name }}"
      validate_certs: no
    register: download_result
    until: download_result is success
    retries: 2
    delay: 30

  - 
    name: "Download Nvidia driver"
    win_get_url:
      url: "{{ nvidia_installer_url }}"
      dest: "{{ required_software_path }}\\{{ nvidia_installer_name }}"
      validate_certs: no
    register: download_result
    until: download_result is success
    retries: 2
    delay: 30
    when: gpu_type == "Nvidia"
  
  - 
    name: "Download Amd driver"
    win_get_url:
      url: "{{ amd_installer_url }}"
      dest: "{{ required_software_path }}\\{{ amd_installer_name }}"
      validate_certs: no
    register: download_result
    until: download_result is success
    retries: 2
    delay: 30
    when: gpu_type == "Amd"
  
  - 
    name: "Unzip Amd installer" # Seems win_unzip doesn't like amd.exe for an unknown reason at this time. Need to run 7z via command line.
    win_shell: "7z.exe x {{ required_software_path }}\\{{ amd_installer_name }} -o{{ amd_extract_dir }}"
    args:
      chdir: C:\\Program Files\\7-Zip
    when: gpu_type == "Amd"

  - 
    name: "Download Cloud Nexis Client installers"
    win_get_url:
      url: "{{ nexis_client_installer_url }}"
      dest: "{{ required_software_path }}\\{{ nexis_client_installer_name }}"
      validate_certs: no
    register: download_result
    until: download_result is success
    retries: 2
    delay: 30
  
  - 
    name: "Download MediaComposer installers"
    win_get_url:
      url: "{{ media_composer_installer_url }}"
      dest: "{{ required_software_path }}\\{{ media_composer_installer_name }}"
      validate_certs: no
    register: download_result
    until: download_result is success
    retries: 2
    delay: 30

  - 
    name: "Debug information: Download installers"
    ansible.builtin.debug:
      var: download_result
      verbosity: 2

  - 
    name: "Unzip Media Composer"
    community.windows.win_unzip:
      src: "{{ required_software_path }}\\{{ media_composer_installer_name }}"
      dest: "{{ required_software_path }}"
    register: unzip_installer_result
    until: unzip_installer_result is success
    retries: 10
    delay: 30

  - 
    name: "Debug information: Unzip Media Composer"
    ansible.builtin.debug:
      var: unzip_installer_result
      verbosity: 2

...
