---
# save to output file: part is duplicated in register.yml, to make sure that if license is consumed - device id will be in out vars

- 
  name: "Set json_content"
  delegate_to: localhost
  set_fact:
    json_content: '{"workspace_id":"{{ nexis_workspace_id }}","nexis_workspace_admin_group_id":"{{ nexis_workspace_admin_group_id }}"}'

- 
  name: "make out vars file"
  delegate_to: localhost
  copy:
    content: "{{ json_content | to_nice_json }}" 
    dest: out-vars.json

- 
  name: "Save out vars file"
  delegate_to: localhost
  template: 
    src: out-vars.json
    dest: out-vars.json
